from setuptools import find_packages, setup

setup(
    name="medical-ai-platform-backend",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.140.0",
        "uvicorn[standard]==0.51.0",
        "sqlalchemy[asyncio]==2.0.51",
        "aiomysql==0.3.2",
        "pymysql==1.2.0",
        "pydantic==2.13.4",
        "pydantic-settings==2.14.2",
        "python-jose[cryptography]==3.5.0",
        "passlib[bcrypt]==1.7.4",
        "bcrypt==4.0.1",
        "python-multipart==0.0.32",
        "openai==1.58.1",
        "email-validator==2.3.0",
        "chromadb==1.5.9",
        "pymupdf==1.28.0",
        "dashscope>=1.20.0",
        "pytest>=7.0.0",
        "pytest-asyncio>=0.21.0",
        "langgraph==1.2.9",
        "langgraph-checkpoint-redis==0.5.1",
        "redis==7.4.1",
        "slowapi>=0.1.9",
    ],
    author="Medical AI Platform Team",
    description="A medical AI platform for clinical consultation evaluation",
    python_requires=">=3.9",
)
