"""Verify GitHub Actions workflow integrity.

Checks:
1. All actions pinned to immutable 40-char SHA
2. Required CI jobs exist
3. Coach job uses structural mode (not live)
4. Load job starts two backend instances
5. Playwright is present for browser E2E
6. Artifact paths are generated by corresponding jobs
7. RC workflow uses live mode (not structural/mock)
8. RC workflow starts full service stack
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

USES_RE = re.compile(r"^\s*-\s+uses:\s*([^\s#]+)", re.MULTILINE)
SHA_RE = re.compile(r"^[0-9a-f]{40}$")

# ── Required job definitions ──────────────────────────────────────────

REQUIRED_CI_JOBS = [
    "backend-quality",
    "frontend-test",
    "migration-gate",
    "structural-coach",
    "safety-corpus",
    "route-auth-contract",
    "mcp-protocol",
    "voice-mock-boundary",
    "playwright-e2e",
]

REQUIRED_RC_JOBS = [
    "validate-input",
    "setup-services",
    "db-migrate-seed",
    "72-case-live",
    "browser-e2e",
    "dual-load",
    "disconnect-replay",
    "migration-verify",
    "evidence-manifest",
]


# ── Pin verification ─────────────────────────────────────────────────

def verify_workflow_pins(workflow_root: Path) -> list[str]:
    """Alias for verify_pins for test compatibility."""
    return verify_pins(workflow_root)


def verify_pins(workflow_root: Path) -> list[str]:
    """Return errors for every non-pinned or non-SHA action reference."""
    errors: list[str] = []
    for path in sorted(Path(workflow_root).glob("*.y*ml")):
        for ref in USES_RE.findall(path.read_text(encoding="utf-8")):
            if ref.startswith("./") or ref.startswith("docker://"):
                continue
            action, separator, revision = ref.rpartition("@")
            if not separator or not action or not SHA_RE.fullmatch(revision):
                errors.append(f"{path.name}: {ref} is not pinned to 40-char SHA")
    return errors


# ── Job existence helpers ─────────────────────────────────────────────

def _extract_job_names(content: str) -> list[str]:
    """Extract top-level job names from a workflow YAML."""
    return re.findall(r"^  ([\w-]+):\s*$", content, re.MULTILINE)


def _extract_job_block(content: str, job_name: str) -> str:
    """Extract the text block for a given job."""
    pattern = re.compile(
        rf"^  {re.escape(job_name)}:\s*\n(.*?)(?=^  [\w-]+:|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    m = pattern.search(content)
    return m.group(0) if m else ""


# ── CI structure checks ──────────────────────────────────────────────

def verify_ci_structure(content: str) -> list[str]:
    errors: list[str] = []
    jobs = _extract_job_names(content)

    # Required jobs must exist
    for required in REQUIRED_CI_JOBS:
        if required not in jobs:
            errors.append(f"CI missing required job: {required}")

    # Coach job must NOT use live mode
    coach_block = _extract_job_block(content, "structural-coach")
    if coach_block:
        if "execution-mode live" in coach_block:
            errors.append("structural-coach must not use execution-mode live")
        if "execution_mode" in coach_block or "execution-mode" in coach_block:
            if "structural" not in coach_block:
                errors.append("structural-coach must use execution-mode structural")

    # Release-eligible must be false in coach output
    if coach_block and "release_eligible" in coach_block:
        if '"release_eligible": true' in coach_block or "'release_eligible': true" in coach_block:
            errors.append("structural-coach must not set release_eligible=true")

    return errors


# ── RC structure checks ──────────────────────────────────────────────

def verify_rc_structure(content: str) -> list[str]:
    errors: list[str] = []
    jobs = _extract_job_names(content)

    # Required jobs must exist
    for required in REQUIRED_RC_JOBS:
        if required not in jobs:
            errors.append(f"RC missing required job: {required}")

    # RC must NOT use structural or mock modes
    if "execution-mode structural" in content or "execution-mode mock" in content:
        errors.append("RC must not use structural or mock execution modes")

    # RC must reference candidate_sha in checkout
    if "inputs.candidate_sha" not in content:
        errors.append("RC must bind to inputs.candidate_sha")

    # RC must start full services (MySQL + Redis + two backends)
    if "mysql" not in content.lower():
        errors.append("RC must start MySQL")
    if "redis" not in content.lower():
        errors.append("RC must start Redis")

    # Load job must start two backend instances
    load_block = _extract_job_block(content, "dual-load")
    if load_block:
        has_dual = (
            ("backend-a" in load_block and "backend-b" in load_block)
            or "8001" in load_block
            or "two" in load_block.lower()
            or "dual" in load_block.lower()
        )
        if not has_dual:
            errors.append("dual-load job must start two backend instances")

    # Must include Playwright for browser E2E
    browser_block = _extract_job_block(content, "browser-e2e")
    if browser_block:
        if "playwright" not in browser_block.lower():
            errors.append("browser-e2e job must use Playwright")

    return errors


# ── Artifact path verification ────────────────────────────────────────

def verify_artifact_paths(content: str) -> list[str]:
    errors: list[str] = []
    jobs = _extract_job_names(content)

    for job_name in jobs:
        block = _extract_job_block(content, job_name)
        if not block:
            continue

        # Find artifact upload paths
        upload_paths = re.findall(
            r"path:\s*\n((?:\s+-[^\n]+\n)*)", block
        )
        single_paths = re.findall(
            r"path:\s*([^\n{][^\n]*)", block
        )

        all_paths: list[str] = []
        for path_block in upload_paths:
            all_paths.extend(
                p.strip().lstrip("- ").strip()
                for p in path_block.strip().split("\n")
                if p.strip()
            )
        all_paths.extend(p.strip() for p in single_paths)

        # Check each artifact path is plausibly generated by a run step
        run_steps = re.findall(r"run:\s*\|[^\n]*\n((?:\s+[^\n]+\n)*)", block)
        run_text = " ".join(run_steps)

        for artifact_path in all_paths:
            if "upload-artifact" in artifact_path:
                continue
            # Extract directory or file hint from path
            path_parts = artifact_path.replace("./", "").split("/")
            hint = path_parts[-1] if path_parts else artifact_path
            hint = hint.replace("*", "").replace(".json", "").replace(".xml", "")
            if len(hint) < 3:
                hint = path_parts[-2] if len(path_parts) > 1 else hint
            if hint and hint not in run_text and hint.lower() not in run_text.lower():
                # Only flag if the path component is completely absent from run steps
                if not any(part in run_text for part in path_parts if len(part) > 2):
                    errors.append(
                        f"Job '{job_name}': artifact path '{artifact_path}' "
                        f"may not be generated by any run step"
                    )

    return errors


# ── Main ──────────────────────────────────────────────────────────────

def main() -> int:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".github/workflows")
    if not target.exists():
        print(f"ERROR: workflow directory not found: {target}")
        return 1

    all_errors: list[str] = []

    # 1. Pin verification (all workflows)
    pin_errors = verify_pins(target)
    all_errors.extend(pin_errors)

    # 2. CI structure
    ci_path = target / "ci.yml"
    if ci_path.exists():
        ci_content = ci_path.read_text(encoding="utf-8")
        all_errors.extend(verify_ci_structure(ci_content))
        all_errors.extend(verify_artifact_paths(ci_content))
    else:
        all_errors.append("ci.yml not found")

    # 3. RC structure
    rc_path = target / "v12-rc.yml"
    if rc_path.exists():
        rc_content = rc_path.read_text(encoding="utf-8")
        all_errors.extend(verify_rc_structure(rc_content))
        all_errors.extend(verify_artifact_paths(rc_content))
    else:
        all_errors.append("v12-rc.yml not found")

    # Report
    if all_errors:
        print("WORKFLOW VERIFICATION FAILED:")
        for err in all_errors:
            print(f"  ERROR: {err}")
        return 1

    print("All workflow structure checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
