"""baseline current schema

Revision ID: 0c1dfb4fea5f
Revises:
Create Date: 2026-07-25 23:18:43.508455

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0c1dfb4fea5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.Enum('login', 'create_consultation', 'submit_diagnosis', 'trigger_evaluation', 'admin_action', name='audit_action_type'), nullable=False, comment='操作类型'),
    sa.Column('resource_id', sa.String(length=50), nullable=True, comment='关联资源ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='客户端IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='客户端UA'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情（脱敏）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('evaluation_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_checkpoints_evaluation_id'), 'evaluation_checkpoints', ['evaluation_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='模型配置'),
    sa.Column('status', sa.Enum('active', 'inactive', 'deprecated', name='model_version_status'), nullable=False, comment='状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('score_adjustments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_evaluation_id'), 'review_records', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_review_records_reviewer_id'), 'review_records', ['reviewer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('doctor', 'admin', name='user_role'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='细粒度权限列表'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('virtual_patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_type'), nullable=False),
    sa.Column('personality_type', sa.Enum('配合型', '焦虑型', '沉默型', '对抗型', name='personality_type'), nullable=False, comment='人格类型：配合型/焦虑型/沉默型/对抗型'),
    sa.Column('chief_complaint', sa.String(length=200), nullable=False, comment='主诉'),
    sa.Column('medical_history', sa.Text(), nullable=False, comment='病史'),
    sa.Column('symptoms', sa.Text(), nullable=False, comment='症状描述（JSON）'),
    sa.Column('expected_diagnosis', sa.String(length=200), nullable=True, comment='预期诊断'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='虚拟患者的系统提示词'),
    sa.Column('difficulty_level', sa.Integer(), nullable=True, comment='难度等级 1-5'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'evaluated', name='consultation_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True, comment='医生提交的诊断结果'),
    sa.Column('treatment_plan', sa.Text(), nullable=True, comment='医生提交的治疗方案'),
    sa.Column('consultation_type', sa.String(length=20), nullable=False, comment='问诊类型: initial/follow_up/communication'),
    sa.Column('max_rounds', sa.Integer(), nullable=True, comment='最大允许问诊轮次'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['virtual_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'patient', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='消息序号'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    op.create_table('evaluation_locks',
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('consultation_id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='run_id (UUID)'),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('graph_version', sa.String(length=50), nullable=False),
    sa.Column('scoring_policy_version', sa.String(length=50), nullable=False),
    sa.Column('checkpoint_thread_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('selected_agents', sa.JSON(), nullable=True),
    sa.Column('evaluation_plan', sa.JSON(), nullable=True, comment='评估计划（Plan-Execute 模式）'),
    sa.Column('execution_results', sa.JSON(), nullable=True, comment='计划步骤执行结果'),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('inquiry_score', sa.Float(), nullable=True, comment='病史采集评分'),
    sa.Column('inquiry_analysis', sa.Text(), nullable=True, comment='病史采集分析详情'),
    sa.Column('knowledge_score', sa.Float(), nullable=True, comment='医学知识评分'),
    sa.Column('knowledge_analysis', sa.Text(), nullable=True, comment='知识核对详情'),
    sa.Column('humanistic_score', sa.Float(), nullable=True, comment='沟通交流评分'),
    sa.Column('humanistic_analysis', sa.Text(), nullable=True, comment='沟通交流评估详情'),
    sa.Column('diagnosis_score', sa.Float(), nullable=True, comment='诊断结果评分'),
    sa.Column('diagnosis_analysis', sa.Text(), nullable=True, comment='诊断结果评估详情'),
    sa.Column('treatment_score', sa.Float(), nullable=True, comment='治疗方案评分'),
    sa.Column('treatment_analysis', sa.Text(), nullable=True, comment='治疗方案评估详情'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='综合评分'),
    sa.Column('overall_summary', sa.Text(), nullable=True, comment='综合评估摘要'),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('citation_data', sa.JSON(), nullable=True, comment='引用数据'),
    sa.Column('retrieval_status', sa.String(length=20), nullable=False, comment='检索状态'),
    sa.Column('evidence_stance', sa.String(length=20), nullable=False, comment='证据立场'),
    sa.Column('human_review_needed', sa.Boolean(), nullable=False, comment='是否需要人工复核'),
    sa.Column('review_reason', sa.Text(), nullable=True, comment='复核原因'),
    sa.Column('rag_trace_data', sa.JSON(), nullable=True, comment='RAG 追踪数据'),
    sa.Column('evaluation_status', sa.String(length=20), nullable=False, comment='评估状态'),
    sa.Column('run_id', sa.String(length=36), nullable=True, comment='关联的评估运行ID'),
    sa.Column('safety_data', sa.JSON(), nullable=True, comment='Safety检查结果'),
    sa.Column('applicable_dimensions', sa.JSON(), nullable=True, comment='适用维度列表'),
    sa.Column('scoring_policy_version', sa.String(length=50), nullable=True, comment='评分策略版本'),
    sa.Column('graph_version', sa.String(length=50), nullable=True, comment='编排图版本'),
    sa.Column('review_completed_by', sa.String(length=50), nullable=True, comment='复核完成人ID'),
    sa.Column('review_completed_at', sa.DateTime(), nullable=True, comment='复核完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_consultation_id'), 'evaluations', ['consultation_id'], unique=True)
    op.create_table('evaluation_node_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/skipped/error/insufficient'),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_node_results')
    op.drop_index(op.f('ix_evaluations_consultation_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('evaluation_runs')
    op.drop_table('evaluation_locks')
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_table('virtual_patients')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_review_records_reviewer_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_evaluation_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_evaluation_checkpoints_evaluation_id'), table_name='evaluation_checkpoints')
    op.drop_table('evaluation_checkpoints')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
